"use strict";(self.webpackChunkconvenient_service_docs=self.webpackChunkconvenient_service_docs||[]).push([[3759],{2702:(e,r,n)=>{n.r(r),n.d(r,{assets:()=>c,contentTitle:()=>o,default:()=>h,frontMatter:()=>i,metadata:()=>a,toc:()=>l});var t=n(4848),s=n(8453);const i={slug:"/basics/errors",sidebar_position:4,title:"Errors"},o=void 0,a={id:"basics/errors",title:"Errors",description:"Now, it is the time to describe each result type. Let's start with errors.",source:"@site/docs/basics/errors.mdx",sourceDirName:"basics",slug:"/basics/errors",permalink:"/basics/errors",draft:!1,unlisted:!1,editUrl:"https://github.com/marian13/convenient_service_docs/blob/main/docs/basics/errors.mdx",tags:[],version:"current",sidebarPosition:4,frontMatter:{slug:"/basics/errors",sidebar_position:4,title:"Errors"},sidebar:"docs",previous:{title:"Service goals",permalink:"/basics/service_goals"},next:{title:"Failures",permalink:"/basics/failures"}},c={},l=[{value:"What is an error?",id:"what-is-an-error",level:2}];function d(e){const r={a:"a",admonition:"admonition",code:"code",em:"em",h2:"h2",p:"p",pre:"pre",...(0,s.R)(),...e.components};return(0,t.jsxs)(t.Fragment,{children:[(0,t.jsxs)(r.p,{children:["Now, it is the time to describe each result type. Let's start with ",(0,t.jsx)(r.em,{children:"errors"}),"."]}),"\n",(0,t.jsx)(r.h2,{id:"what-is-an-error",children:"What is an error?"}),"\n",(0,t.jsxs)(r.p,{children:[(0,t.jsx)(r.em,{children:"Error"})," is a result type caused either by the wrong input data (",(0,t.jsx)(r.em,{children:"validation error"}),") or by the exceptional behaviour (",(0,t.jsx)(r.em,{children:"exception error"}),")."]}),"\n",(0,t.jsxs)(r.p,{children:["In some cases, it may be a validation rule violation, unsatisfied ",(0,t.jsx)(r.a,{href:"https://wiki.c2.com/?ReplaceCommentWithAssertion",children:"assertion"}),", or unmet precondition based on the service arguments."]}),"\n",(0,t.jsx)(r.p,{children:"It is a responsibility of a developer/service user to provide correct inputs."}),"\n",(0,t.jsx)(r.p,{children:"Otherwise, there is no sense in even starting any service processing."}),"\n",(0,t.jsxs)(r.p,{children:["Also errors are often semantically close to the ",(0,t.jsx)(r.a,{href:"https://ruby-doc.org/core-2.7.0/Exception.html",children:"exceptions"}),"."]}),"\n",(0,t.jsxs)(r.p,{children:["In other words, service errors are frequently located at the same places where ",(0,t.jsx)(r.a,{href:"https://ruby-doc.org/core-2.7.0/Exception.html",children:"exceptions"})," are ",(0,t.jsx)(r.a,{href:"https://ruby-doc.com/docs/ProgrammingRuby/html/tut_exceptions.html",children:"raised/rescued"})," in the reqular methods."]}),"\n",(0,t.jsx)(r.admonition,{type:"info",children:(0,t.jsx)(r.p,{children:"Exceptional behaviour like HTTP connection issues, database inconsistencies, timeouts, etc are also errors."})}),"\n",(0,t.jsx)(r.p,{children:"Check out the following example:"}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-ruby",children:'class EnsureFeatureActive\n  # ...\n  def initialize(name:)\n    @name = name\n  end\n\n  def result\n    return error("Feature name can NOT be `nil`") if name.nil?\n    return error("Unknown feature `#{name}`") unless Feature.exist?(name: name)\n\n    # ... Tricky and non trivial logic to ensure that feature is active...\n  rescue Feature::Exceptions::ConnectionTimeout => exception\n    return error("Feature `#{name}` connection timeout due to `#{exception.message}`")\n  end\nend\n'})}),"\n",(0,t.jsx)(r.p,{children:"And this is how it can be triggerred:"}),"\n",(0,t.jsx)(r.pre,{children:(0,t.jsx)(r.code,{className:"language-ruby",children:'result = EnsureFeatureActive.result(name: "Fancy feature")\n\nif result.error?\n  # `result.message` is a string-like object with error reason.\n  result.message\nend\n'})}),"\n",(0,t.jsxs)(r.p,{children:["There is no point to involve all the heavy machinery when the feature name is ",(0,t.jsx)(r.code,{children:"nil"}),"."]}),"\n",(0,t.jsx)(r.p,{children:"Why do we need to waste any expensive resources if the feature name is unknown?"}),"\n",(0,t.jsx)(r.p,{children:"Can we guarantee whether the feature is actually active when a connection timeout happens?"}),"\n",(0,t.jsx)(r.p,{children:"So, the one of the purposes of the error result is to say that the callers need to make adjustments in their code/config/dependency, not the service authors."})]})}function h(e={}){const{wrapper:r}={...(0,s.R)(),...e.components};return r?(0,t.jsx)(r,{...e,children:(0,t.jsx)(d,{...e})}):d(e)}},8453:(e,r,n)=>{n.d(r,{R:()=>o,x:()=>a});var t=n(6540);const s={},i=t.createContext(s);function o(e){const r=t.useContext(i);return t.useMemo((function(){return"function"==typeof e?e(r):{...r,...e}}),[r,e])}function a(e){let r;return r=e.disableParentContext?"function"==typeof e.components?e.components(s):e.components||s:o(e.components),t.createElement(i.Provider,{value:r},e.children)}}}]);